# Numpy

## 1. Numpy arrays

fl_sp bevat de oppervlaktes in vierkante meters van 5 winkels.   
turnover bevat de omzet in Britse Ponden (GBP) van dezelfde 5 winkels (in dezelfde volgorde).

- Importeer Numpy.
- Zet de lists om in de Numpy arrays np_fl en np_to.
- Print de types van de arrays.
- Maak een nieuwe array to_eur aan waarin de omzetten worden omgezet in Euro bedragen. 
    - Zoek de wisselkoers op op het Internet.  
- Print to_eur.
- Bereken de EUR omzet per vierkante meter per winkel in de nieuwe array to_sqm.
- Print de eerste 3 regels van to_sqm
- Als de omzet per vierkante meter hoger is dan 230 dan wordt dit als 'goed' gezien. Print de elementen die hoger zijn dan deze grenswaarde.
- Print de hoogste omzet per vierkante meter.

In [8]:
import numpy as np

In [14]:
fl_sp = [18526, 18569, 12288, 17092, 11307]
turnover = [3410865, 4034051,2297810, 2398990, 2288235]
import numpy as np
#Import:
np_fl = np.array(fl_sp)
np_turnover = np.array(turnover)

#Convert to EUR and print
to_eur = np_turnover *1.19

#Calculate EUR turnover per sqm and print first 3 items
persqm = to_eur/fl_sp
print(persqm[0:3])


#Print to per sqm > 230

print(persqm[persqm>230])



#Print the highest turnover
print(max(np_turnover))

[219.09367106 258.52338252 222.52554525]
[258.52338252 240.8242372 ]
4034051


## 2 Numpy 2D arrays
De list met lists fl_sp_to bevat de oppervlaktes in vierkante meters en de omzetten in GBP van 5 winkels.
- Zet fl_sp_to om in een 2D Numpy array.
- Laat zien hoeveel rijen en kolommen fl_sp bevat.
- Print de tweede kolom van de laatste 4 regels.
- Print de tweede rij tot en met de vierde rij.
- Converteer de vloeroppervlaktes naar square feet (i.p.v. vierkante meters) en de GBP bedragen naar EUR. Zoek de juiste omrekenfactoren op op het internet. De nieuwe array krijgt als naam conv.
- Print conv.
- Elke winkelmanager krijgt een bonus. De bonus percentages staan in de bonus list. Het bonusbedrag is het  bonuspercentage maal de omzet. Maak de array bon_amount met daarin de vloeroppervlaktes en de bonus bedragen. Zet hiervoor eerst de bonus list om in een array. Gebruik deze array bij het maken van bon_amount.
- Print bon_amount.

In [30]:
fl_sp_to = [[18526, 3410865],
            [18569, 4034051],
            [12288, 2297810], 
            [17092, 2398990], 
            [11307, 2288235]]
#Convert into a 2D array
np_sp = np.array(fl_sp_to)

#print second column of last 4 rows
#print(np_sp[1:, 1])
#print second row up to and including the 4th row
print(np_sp[1:4, :])
#Convert to square feet and EUR
conversion = np.array([2, 4])
convert = np_sp * conversion
print(convert)
#Bonus table
bonus = [[1, 0.010],
         [1, 0.008],
         [1, 0.007], 
         [1, 0.011], 
         [1, 0.005]]
# bonus amount



[[  18569 4034051]
 [  12288 2297810]
 [  17092 2398990]]
[[   37052 13643460]
 [   37138 16136204]
 [   24576  9191240]
 [   34184  9595960]
 [   22614  9152940]]


## 3 Integratie opdracht

In onderstaande cel worden winkelgegevens geimporteerd uit een csv-bestand met behulp van Pandas. Dit is iets waar we de komende lessen veel dieper op in gaan. Het resultaat is dat er een 2D numpy array st_to beschikbaar is voor deze opdracht.

In st_to vind je het aantal medewerkers (staff members) en de omzet (turnover) per winkel. We verwachten dat er een verband is tussen het aantal medewerkers en de omzet. Dat gaan we nu onderzoeken.

- Bereken het gemiddelde, de mediaan en de standaarddeviatie van beide kolommen.
- Wat valt je op aan deze waardes?
- Print de array. Zijn er waardes die sterk afwijken? Welke zijn dat?
- Print de regels uit st_to die hetzelfde aantal medewerkers hebben als het mediane aantal medewerkers.
- Print de correlatiecoefficient voor beide kolommen.
- Welke opties zijn er om de datakwaliteit te verhogen?

In [31]:
#Don't remove this:
import pandas as pd
import numpy as np
storedata = pd.read_csv('storedata.csv', encoding = 'ISO-8859-1')
st_to = storedata[['Staff', 'Profit']].values

# Start coding here:
# Staff


# Turnover


#print the array and investigate:


#print the lines that have a staff number that is the same as the median:


#correlatiecoefficient



FileNotFoundError: [Errno 2] No such file or directory: 'storedata.csv'